name: Publish
on:
  release:
    types: [released]
jobs:
  publish:
    name: Publish
    if: github.event_name == 'release'
    uses: CumulusDS/workflows/.github/workflows/package-publish.yml@master
    secrets: inherit
